kind: Deployment
apiVersion: apps/v1
metadata:
  name: canary-deploy
  spec:
  replicas:
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      name: newapp
      labels:
        app: newapp
        env: canary
    spec:
      containers:
      - name: newapp
        image: mynewcont.azurecr.io/newapp:v2
      imagePullSecrets:
      - name: secret
---
kind: Service
apiVersion: v1
metadata:
  name: newapp
  labels:
    name: newapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: newapp

