kind: Deployment
apiVersion: apps/v1
metadata:
  name: newapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp 
  template:
    metadata:
      name: newapp
      labels:
        app: newapp
        env: prod0
    spec:
      containers:
      - name: newapp
        image: mynewcont.azurecr.io/newapp:v2
      imagePullSecrets:
      - name: secret
---
kind: Service
apiVersion: v1
metadata:
  name: newapp
  labels:
    name: newapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: newapp
