apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deployment
  labels:
    app: newapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - name: newapp
        image: mynewcont.azurecr.io/newapp:v1
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: newapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: newapp
