kind: Deployment
apiVersion: apps/v1
metadata:
  name: nowapka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nowapka 
  template:
    metadata:
      name: nowapka
      labels:
        app: nowapka
        env: prod2
    spec:
      containers:
      - name: nowapka
        image: mynewcont.azurecr.io/nowapka:v1
      imagePullSecrets:
      - name: secret
---
kind: Service
apiVersion: v1
metadata:
  name: nowapka
  labels:
    name: nowapka
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: nowapka
